# Generated by Django 4.2.1 on 2023-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_profile_img',
            field=models.ImageField(null=True, upload_to='comment_profile_images/'),
        ),
    ]
